export enum HttpResponseStatus {
  OK = 200,
  CREATED = 201,
  NO_CONTENT = 204,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  UNSUPPORTED_MEDIA_TYPE = 415,
  UNPROCESSABLE_ENTITY = 422,
  INTERNAL_SERVER_ERROR = 500,
  NOT_IMPLEMENTED = 501,
}

export const ROUTE_PATHNAME_PARAM_NAME_REGEXP_PATTERN =
  "[a-zA-Z_][a-zA-Z0-9_]*";
export const ROUTE_PATHNAME_PARAM_SLOT_REGEXP_PATTERN = ":" +
  ROUTE_PATHNAME_PARAM_NAME_REGEXP_PATTERN;
export const ROUTE_PATHNAME_PARAM_WILDCARD_REGEXP_PATTERN =
  `/?\\*\\{${ROUTE_PATHNAME_PARAM_NAME_REGEXP_PATTERN}\\}`;
export const REQUEST_PATHNAME_PARAM_VALUE_REGEXP_PATTERN = "[a-zA-Z0-9+=*&_-]+";
export const REQUEST_PATHNAME_PARAM_WILDCARD_VALUE_REGEXP_PATTERN =
  `(${REQUEST_PATHNAME_PARAM_VALUE_REGEXP_PATTERN}/?)*`;
export const REQUEST_PATHNAME_PARAM_WILDCARD_WITH_LEADING_FORWARD_SLASH_VALUE_REGEXP_PATTERN =
  `(/${REQUEST_PATHNAME_PARAM_WILDCARD_VALUE_REGEXP_PATTERN})*`;
